### ISSUE TITLE
Shouldn't try to add a testing policy when one is present

### ISSUE THREAD

**Issue by gijsk** [nchevobbe/phab-test-policy#3]
This is a little unfortunate - if I accept a revision that has a testing policy added already (e.g. if I've accepted and added a policy before, and then the author re-requests review), the add-on forces a new row to be added and adds "testing-" to the row. So I have to remove that. I can't remove the row entirely - it just comes back. But if I remove the "testing-" and then click accept, phab warns that one of the actions has no effect.

Seems that if the revision has a test policy tag already we shouldn't enforce adding the action.

**Comment by nchevobbe** [comment]
I thought I was handling this (see https://github.com/nchevobbe/phab-test-policy/blob/f5bfa1f297694e4596ca8fdd3e72b4bbfcfdb169/test-policy.js#L34-L48) but maybe I missed something

**Comment by gijsk** [comment]
I think it checks whether the outgoing request has a project tag, but if the revision already has one (not added in the same submission of several actions) then it might not show up in there, I guess? Perhaps only if not added by me (can happen when there are multiple reviewers), or something?

**Comment by nchevobbe** [comment]
good point, I'll check this case in a bit
