### ISSUE TITLE
Selecting Change Reviewers before accepting the revision causes the testing tag to be added in the reviewers section

### ISSUE THREAD

**Issue by Standard8** [nchevobbe/phab-test-policy#6]
STR

1. Enter a phabricator revision
2. Select `Change Reviewers` (as you want to approve, but also add someone else)
3. Select `Accept Revision`

Expected Results

* The testing policy tags attempt to be added to the "Change Project Tags" field.

Actual Results

* The testing policy tags attempt to be added to the "Change Reviewers" field.

**Comment by nchevobbe** [comment]
Thanks for the report, I do reproduce.
The issue is that there's no explicit attribute that distinguish the reviewers from the project tags input :/
I might check the label text, but that's a bit ugly, I'll try to see if I can do better

**Comment by nchevobbe** [comment]
this was fixed in 1.4.0 , which is now on AMO
